// <auto-generated />
using System;
using Fiap.Api.MVPSaude.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fiap.Api.MVPSaude.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Fiap.Api.MVPSaude.Model.MedicoModel", b =>
                {
                    b.Property<int>("MedicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MEDICOID");

                    b.Property<string>("Contato")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("CONTATO");

                    b.Property<string>("Crm")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CRM");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ESPECIALIDADE");

                    b.Property<string>("NomeMedico")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("NOMEMEDICO");

                    b.HasKey("MedicoId");

                    b.ToTable("MEDICO");
                });

            modelBuilder.Entity("Fiap.Api.MVPSaude.Model.PacienteModel", b =>
                {
                    b.Property<int>("PacienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PACIENTEID");

                    b.Property<string>("Contato")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("CONTATO");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CPF");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATANASCIMENTO");

                    b.Property<string>("Endereco")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("ENDERECO");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("GENERO");

                    b.Property<string>("NomePaciente")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("NOMEPACIENTE");

                    b.HasKey("PacienteId");

                    b.ToTable("PACIENTE");
                });

            modelBuilder.Entity("Fiap.Api.MVPSaude.Model.ProntuarioModel", b =>
                {
                    b.Property<int>("ProntuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PRONTUARIOID");

                    b.Property<DateTime>("DataProntuario")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATAPRONTUARIO");

                    b.Property<string>("Exames")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("EXAMES");

                    b.Property<string>("HistFamiliar")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("HISTORICOFAMILIAR");

                    b.Property<string>("HistPaciente")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("HISTORICOPACIENTE");

                    b.Property<string>("Medicamento")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("MEDICAMENTO");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int")
                        .HasColumnName("MEDICOID");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int")
                        .HasColumnName("PACIENTEID");

                    b.Property<string>("Triagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("TRIAGEM");

                    b.HasKey("ProntuarioId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.ToTable("PRONTUARIO");
                });

            modelBuilder.Entity("Fiap.Web.MVPSaude.Models.ConsultaModel", b =>
                {
                    b.Property<int>("ConsultaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CONSULTAID");

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATACONSULTA");

                    b.Property<string>("HoraConsulta")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("HORACONSULTA");

                    b.Property<string>("LocalConsulta")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("LOCALCONSULTA");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int")
                        .HasColumnName("MEDICOID");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("MENSAGEM");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int")
                        .HasColumnName("PACIENTEID");

                    b.HasKey("ConsultaId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.ToTable("CONSULTA");
                });

            modelBuilder.Entity("Fiap.Web.MVPSaude.Models.UsuarioModel", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("USUARIOID");

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("EMAILUSUARIO");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NOMEUSUARIO");

                    b.Property<string>("SenhaUsuario")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("SENHAUSUARIO");

                    b.HasKey("UsuarioId");

                    b.ToTable("USUARIO");
                });

            modelBuilder.Entity("Fiap.Api.MVPSaude.Model.ProntuarioModel", b =>
                {
                    b.HasOne("Fiap.Api.MVPSaude.Model.MedicoModel", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fiap.Api.MVPSaude.Model.PacienteModel", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Fiap.Web.MVPSaude.Models.ConsultaModel", b =>
                {
                    b.HasOne("Fiap.Api.MVPSaude.Model.MedicoModel", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fiap.Api.MVPSaude.Model.PacienteModel", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });
#pragma warning restore 612, 618
        }
    }
}
